version: "2"
services:
  article-docker:
    container_name: articles-docker
    restart: always
    build: .
    ports:
      - "3040:3040"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"