# POST http://localhost:3040/api/v1/articles/create 
# Content-Type: application/json

# {
#     "title": "one", "content" : "this is the first test"
# }

POST http://localhost:3040/api/v1/task/create
Content-Type: application/json

{

    "title":"laundry 2.0",
    "message" : "clean clothes maketh the man",
    "category" : "priority"

}